# str1='python'
# print(max(str1))
# print(min(str1))
# print(len(str1))
# print(id(str1))
# print(type(str1))

# print(ord(' '))
# print(ord('0'))
# print(ord('9'))
# print(ord('A'))  
# print(ord('Z'))
# print(ord('a'))
# print(ord('z'))
# x=input("Enter your name")
print(chr(32))
print(chr(65))
