sr1='I Love Python'
print(sr1.lower())
print(sr1.upper())
print(sr1.swapcase())
print(sr1.title())
print(sr1.capitalize())
print(sr1.count('o'))
# print(sr1.index('p'))
print(sr1.index('P'))
print(sr1.find('P'))
print(sr1.find('p'))